### ISSUE TITLE
The "#r" syntax in c# is amazing, I want to learn the principle

### ISSUE THREAD

**Issue by thouger** [elm-fullstack/elm-fullstack#21]
First of all, why running the elm-fs command will compile the c# language. I probably read at the code, but I didn't find the point.
Secondly, what using of syntax is "`#r`", why it can import sha256, and why it uses `#r "System"` once and then `uses System`;

the "#r" is rare, I think this is a very creative thing.

**Comment by Viir** [comment]
We use C# to reach various platforms and compilation targets: Linux, Windows, MacOS, WebAssembly, ...

The `#r` is syntax to reference an assembly. This functionality comes with the standard Roslyn C# compiler.

> why it can import sha256

Because I added support for this. This variant is not in the standard Roslyn C# compiler.
I added the `sha256` variant of assembly references to enable safe/deterministic references.

> the "#r" is rare, I think this is a very creative thing.

I found an article describing this feature: https://learn.microsoft.com/en-au/archive/blogs/cdndevs/adding-c-scripting-to-your-development-arsenal-part-1

Following is an excerpt:

> Finally, there are two new extra feature worth mentioning, and these are new compiler directive, #load and #r. They are only allowed to be used in C# script code (would not work with "classic" C# syntax), and allow you to reference a script from another script ( #load) and import an assembly reference from GAC or from a path ( #r).

**Comment by thouger** [comment]
Thank you for your answer. I have read them all. I feel that this usage is relatively new. What is even more amazing is that you have matured this usage into a project. Your open source spirit is awesome. "bots+elm-fs+Sanderling"really worth learning
